package com.appcloos.mimaletin.model.CXC

data class ke_precobradocs(
    var cxcndoc: String = "",
    var agencia: String = "",
    var tipodoc: String = "",
    var documento: String = "",
    var bscobro: Double = 0.00,
    var prccobro: Double = 0.00,
    var prcdsctopp: Double = 0.00,
    var nroret: String = "",
    var fchemiret: String = "",
    var bsretiva: Double = 0.00,
    var refret: String = "",
    var nroretfte: String = "",
    var fchemirfte: String = "",
    var bsmtofte: Double = 0.00,
    var bsretfte: Double = 0.00,
    var refretfte: String = "",
    var pidvalid: String = "",
    var bsmtoiva: Double = 0.00,
    var retmun_bi: Double = 0.00,
    var retmun_cod: String = "",
    var retmun_nro: String = "",
    var retmun_mto: Double = 0.00,
    var retmun_fch: String = "",
    var retmun_ref: String = "",
    var diascalc: Double = 0.00,
    var prccomiv: Double = 0.00,
    var prccomic: Double = 0.00,
    var cxcndoc_aux: String = "",
    var tnetodbs: Double = 0.00,
    var tnetoddol: Double = 0.00,
    var fchrecibod: String = "",
    var kecxc_idd: String = "",
    var tasadiad: Double = 0.00,
    var afavor: Double = 0.00,
    var reten: Int = 0
)
